pool:
  vmImage: 'ubuntu-latest'
trigger:
  - master/CodeTech.Toolkit.Serializers/*.csproj
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/CodeTech.Toolkit.Serializers/*.csproj'
    arguments: '-o "$(Build.ArtifactStagingDirectory)"'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'