resources:
 repositories:
   - repository: utiities
     type: git
     name: Utilities

pool:
  vmImage: 'ubuntu-latest'
trigger:
  - master/CodeTech.Toolkit.Serializers/*.csproj
steps:
  - template: utiities/ProjectBuildTemplate.yaml@templates
    parameters: 
      buildfolderName: CodeTech.Toolkit.Serializers