resources:
 repositories:
   - repository: utilities
     type: git
     name: Utilities

pool:
  vmImage: 'ubuntu-latest'
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - CodeTech.Toolkit.Serializers/*
steps:
  - template: BuildTemplates/ProjectBuildTemplate.yaml@utilities
    parameters: 
      buildfolderName: CodeTech.Toolkit.Serializers
      configuration: Debug
      