resources:
 repositories:
   - repository: utilities
     type: git
     name: Utilities

pool:
  vmImage: 'ubuntu-latest'
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - CodeTech.Toolkit.Intervals/*
steps:
  - checkout: self
  - checkout: Utilities
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '5.4.0'
  - template: BuildTemplates/TestAndBuildNetCoreProject.yaml@utilities
    parameters: 
      sourceDirectory: $(Build.SourcesDirectory)/CodeTech.Toolkit
      buildfolderName: CodeTech.Toolkit.Intervals
      configuration: Debug
      outputFolder: $(Build.ArtifactStagingDirectory)      
  - template: BuildTemplates/CreateNuGetPackage.yaml@utilities
    parameters: 
      packageContentFolder: $(Build.ArtifactStagingDirectory)
      packageIcon: Utilities/Images/CodeTechToolkitLogo.png
      nuSpecFolder: $(Build.SourcesDirectory)/CodeTech.Toolkit/CodeTech.Toolkit.Intervals
      outputFolder: $(Build.ArtifactStagingDirectory)
      desiredPackageFileName: CodeTech.Toolkit.Intervals.nupkg
  - task: PowerShell@2
    displayName: Move package to output folder
    inputs:
      targetType: 'inline'
      script: 'Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)" -Exclude "CodeTech.Toolkit.Intervals.nupkg" | Remove-Item -Recurse -Force'
  - task: PublishBuildArtifacts@1
    displayName: Deliver NuGet package as an artifact
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'