resources:
 repositories:
   - repository: utilities
     type: git
     name: Utilities

pool:
  vmImage: 'ubuntu-latest'
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - CodeTech.Toolkit.Extensions/*
steps:
  - template: BuildTemplates/TestAndBuildNetCoreProject.yaml@utilities
    parameters: 
      buildfolderName: CodeTech.Toolkit.Extensions
      configuration: Debug
      outputFolder: $(Build.ArtifactStagingDirectory)
  - template: BuildTemplates/CreateNuGetPackage.yaml@utilities
    parameters: 
      packageContentFolder: $(Build.ArtifactStagingDirectory)
      nuSpecFolder: $(Build.SourcesDirectory)/CodeTech.Toolkit.Extensions
      outputFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: Deliver NuGet package as an artifact
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'