resources:
 repositories:
   - repository: utilities
     type: git
     name: Utilities

pool:
  vmImage: 'ubuntu-latest'
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - CodeTech.Toolkit.Extensions/*
steps:
  - template: ProjectBuildTemplate.yaml@utilities
    parameters: 
      buildfolderName: CodeTech.Toolkit.Extensions