resources:
 repositories:
   - repository: utilities
     type: git
     name: Utilities

pool:
  vmImage: 'ubuntu-latest'
trigger:
  - master/CodeTech.Toolkit.Limits
steps:
  - template: ProjectBuildTemplate.yaml@utilities
    parameters: 
      buildfolderName: CodeTech.Toolkit.Limits